sonar.host.url=https://sonar.testes.com.br/
sonar.projectKey={PROJECT_NAME}
sonar.projectVersion={TAG}
sonar.sourceEncoding=UTF-8
sonar.language=js
# path to source directories
sonar.sources=/usr/src/src
#sonar.tests=scripts/test/*
# excludes
sonar.exclusions=node_modules/*,docs/*,build/*
